import Foundation

/// Campaign registry. The production campaign is `handAuthored + generated`;
/// `debugFixtures` are engineering probes for LevelForge + `LuauSelfTest`.
///
/// Hand-authored levels (L1–L12) live in `LuauLevels.hand.swift`. Generated
/// levels (L13–Lend) are emitted by LevelForge into `LuauLevels.generated.swift`
/// (that file starts empty and is regenerated by
/// `swift run levelforge campaign build`).
enum LuauLevels {

    /// The full campaign in play order — teaching arc first, generated
    /// levels after (Stage C ordering rule: no archetype twice in a row).
    /// GENERATED NIGHTS THAT CARRY A COCONUT. Held here as an overlay rather
    /// than edited into LuauLevels.generated.swift, because that file is emitted
    /// by LevelForge's `campaign build` and a regeneration would silently drop
    /// hand-added fields — the same class of loss that made `LuauLevel.with(...)`
    /// necessary for the solver's own re-staging.
    ///
    /// PLACEMENT, measured rather than guessed. Every id here clears the same
    /// bar: a draining column at least 5 deep, three or more draining columns so
    /// steering has options, and a greedy win rate at or above 60% — cargo ADDS
    /// an objective, so a level with no headroom is the wrong host.
    ///
    /// The shape is a cluster then a sprinkle. L42-L44 are consecutive, sit in a
    /// tight difficulty band (71-74%) so the cluster reads as one idea, and open
    /// the longest run of cargo-viable levels in the campaign (L42-L50). The
    /// lesson goes in front of them, behind L41 — which at 59.5% is the local
    /// difficulty spike and the wrong place to land something new. L48 (87.8%,
    /// the most forgiving level in the region) is a victory lap a few nights
    /// later. After that, roughly every 10-18 nights, tightening through the
    /// upper half where the measured curve flattens and novelty is worth most.
    /// Night id -> EXTRA moves granted for carrying the coconut. Solved against
    /// the calibrating bot so each host plays at the win rate it had before cargo
    /// (within 3pp), and held here so `LuauLevels.generated.swift` stays exactly
    /// what `campaign build` emitted.
    ///
    /// TEN OF SEVENTEEN NEED NOTHING, which is the whole argument that these are
    /// the right hosts. The first pass demanded up to +26 moves — but that was
    /// measuring a bot that did not pursue the objective at all, clearing sand
    /// greedily and waiting for delivery to happen by accident. Teaching it to dig
    /// beneath the coconut (LuauBot.cargoDrop) collapsed L48 from +26 to 0 and
    /// L188 from +24 to +2. L141 wanted +12 on a base of 14 even then, so it was
    /// dropped for L142: doubling a tight level's budget changes what the level
    /// IS, and a neighbour that costs nothing is strictly better.
    static let cargoExtraMoves: [Int: Int] = [
        42: 6, 43: 2, 44: 0, 48: 0, 55: 2, 68: 0, 85: 2,          // intro + early
        101: 2, 112: 0, 122: 0, 130: 0, 142: 0, 152: 0,           // the flat upper half
        165: 2, 178: 0, 188: 2, 196: 0,
    ]

    static var cargoNights: Set<Int> { Set(cargoExtraMoves.keys) }

    /// Where a retrofitted coconut starts: three rows above the shore, in the
    /// draining column nearest the middle. DERIVED, not hand-listed, so every
    /// structural invariant — in range, playable, its column reaches the shore,
    /// and not already delivered on row 6 — holds by construction instead of
    /// resting on seventeen hand-checked indices.
    ///
    /// THE JOURNEY LENGTH IS THE COST, and that is measured, not assumed. Placing
    /// the coconut at the column's TOP row — the obvious choice, and the first
    /// one tried — maximises the descent, and on tight-budget nights the bill was
    /// brutal: restoring L188 to its original win rate wanted +30 moves on a base
    /// of 18, turning a tight puzzle into a long grind. A fixed shallow drop
    /// costs about the same on every host regardless of how deep its column runs,
    /// which is what keeps the budget adjustments small enough to leave each
    /// level recognisably itself.
    static func cargoCell(for level: LuauLevel) -> Int? {
        let draining = (0..<LuauLevel.size).filter { level.drains(col: $0) }
        guard let col = draining.min(by: { abs($0 - 3) < abs($1 - 3) }),
              let top = level.playableRows(col: col).first
        else { return nil }
        let row = max(top, LuauLevel.size - 4)          // three above the shore
        guard row != LuauLevel.size - 1 else { return nil }
        return row * LuauLevel.size + col
    }

    static var all: [LuauLevel] {
        var levels = (handAuthored + generated).map { lv -> LuauLevel in
            guard let extra = cargoExtraMoves[lv.id], let cell = cargoCell(for: lv) else { return lv }
            return lv.with(moves: lv.moves + extra, movesHard: lv.movesHard + extra)
                .with(ingredients: [cell])
        }
        // Lessons that belong INSIDE the generated stretch. Declared as "before
        // night N" and spliced by position, never by id, so no night is ever
        // renumbered and every saved `completedLevels` keeps meaning exactly
        // what it meant. Descending order so each insert cannot shift the index
        // the next one is looking for.
        for entry in insertedLessons.sorted(by: { $0.beforeNight > $1.beforeNight }) {
            guard let i = levels.firstIndex(where: { $0.id == entry.beforeNight }) else { continue }
            levels.insert(entry.lesson, at: i)
        }
        return levels
    }

    /// Cargo lands before Night 77 — deep enough that the campaign has gone
    /// quiet (the measured curve plateaus after Night 100 and "minimal new
    /// pieces" was the actual complaint), and just ahead of the frontier a real
    /// save is sitting at. Move the number to move the lesson; nothing else
    /// changes, because the splice is positional and renumbers nothing.
    ///
    /// A lesson placed BEHIND a player's frontier is invisible to them —
    /// `frontierIndex` takes the max completed position, so anything earlier is
    /// simply skipped. That is correct for shipping (nobody gets dragged
    /// backwards) but it means this number has to lead a live save, not match it.
    private static let insertedLessons: [(beforeNight: Int, lesson: LuauLevel)] = [
        // The corner comes EARLY, unlike cargo. Cargo is a per-level mechanic
        // that only appears on the nights that declare it, so its lesson can
        // wait until just ahead of those nights. A bomb can spawn on Night 1
        // — the moment a player bends five pieces into an L by accident — so
        // teaching it late means shipping an unexplained special. Night 8
        // leaves a few ordinary nights after the scripted coach before
        // introducing a third idea.
        (beforeNight: 8, lesson: cornerLesson),
        (beforeNight: 42, lesson: cargoLesson),
    ]

    // MARK: play order

    /// Position of a level in the campaign, or nil if it is not in it.
    ///
    /// PLAY ORDER IS THE ORDER OF `all`, NOT ID ARITHMETIC. Everything used to
    /// derive order by adding 1 to a level id, which silently required ids to
    /// be contiguous and monotonic — so a level could never be INSERTED
    /// anywhere except the end. Renumbering to make room is not an option
    /// either: `completedLevels` persists level IDs, so shifting 5...200 up by
    /// one would hand every existing player someone else's progress.
    ///
    /// Going through position instead means a teaching level can carry an id
    /// well outside the 1...200 campaign range and still sit between Night 4
    /// and Night 5, with saved progress untouched.
    static func playIndex(of id: Int) -> Int? {
        all.firstIndex { $0.id == id }
    }

    /// The night number a level shows to the player: its 1-based position among
    /// NON-lesson levels. Nil for a lesson, which is never numbered.
    ///
    /// Night numbers are computed rather than read off `id` so that inserting a
    /// lesson never shifts what the player calls Night 5 — the campaign still
    /// reads as its authored number of nights no matter how many lessons sit
    /// between them.
    static func nightNumber(of id: Int) -> Int? {
        var n = 0
        for level in all {
            if level.isLesson { if level.id == id { return nil }; continue }
            n += 1
            if level.id == id { return n }
        }
        return nil
    }

    /// Position of the next level the player has not cleared: one past the
    /// furthest-along level they have. Reads positions rather than max(id) so
    /// clearing an out-of-range teaching level still advances the frontier.
    static func frontierIndex(completed: [Int]) -> Int {
        let furthest = completed.compactMap { playIndex(of: $0) }.max()
        return (furthest ?? -1) + 1
    }

    /// The level at the frontier, clamped to the last authored one.
    static func frontierLevel(completed: [Int]) -> LuauLevel? {
        let levels = all
        guard !levels.isEmpty else { return nil }
        return levels[min(frontierIndex(completed: completed), levels.count - 1)]
    }

    /// The level that follows `id` in play order, nil at the end.
    static func next(after id: Int) -> LuauLevel? {
        guard let i = playIndex(of: id) else { return nil }
        let levels = all
        return i + 1 < levels.count ? levels[i + 1] : nil
    }

    static func level(id: Int) -> LuauLevel? {
        #if DEBUG
        // Debug fixtures resolve too (ids 1001+, never collide with the
        // campaign) so staging hooks and the self-test's save/restore
        // paths treat them as real levels.
        if let dbg = debugFixtures.first(where: { $0.id == id }) { return dbg }
        #endif
        return all.first { $0.id == id }
    }

    // MARK: hand-authored (Stage C teaching arc)
    // Definitions live in LuauLevels.hand.swift so this file stays a
    // registry. `handAuthored` = [L1 ... L12] there.

    // MARK: generated (Stage C generation run)
    // Definitions live in LuauLevels.generated.swift, emitted by the
    // LevelForge `campaign build` subcommand. Empty by default so the
    // app builds cleanly before generation has been run.
    // (See LuauLevels+generated.swift.)

    // MARK: debug fixtures (Stage A/B verification)

    /// The four probe levels the Stage B solver verifies. Each exercises a
    /// distinct constraint: full-board vanilla (easy), a lightly-jellied
    /// well (mask + pocket), a corner-jelly board (edge cells vs cascade
    /// alley), and a 6-color tight board (graduation-lite). All are
    /// engineered to be solvable by the greedy bot — real campaign levels
    /// get much more jelly.
    static let debugFixtures: [LuauLevel] = [debugL1, debugWell, debugCorners, debugShelf6, debugCargo]

    /// Cargo probe. Full board so every column reaches the shore, one piece
    /// of cargo starting at the top of column 3, and no sand — so the ONLY
    /// thing gating the win is delivery. Registered here (rather than left
    /// private to the tests) because save/restore resolves a level by id, so
    /// a fixture that isn't in the registry can never exercise Case A.
    static let debugCargo: LuauLevel = {
        let (m, j) = LuauLevel.parse([
            "#######", "#######", "#######", "#######", "#######", "#######", "#######",
        ])
        return LuauLevel(id: 1005, mask: m, jelly: j, colors: 5,
                         moves: 30, movesHard: 24, seed: 0x1005_1005_1005_1005,
                         archetype: "Full Board", ingredients: [3])
    }()

    /// L1 shape — Full Board with three center jelly cells. Bot-solvable in
    /// a handful of moves; used for baseline determinism + jelly-clears-by-
    /// match tests. Uses id=1001 so it doesn't collide with the campaign.
    static let debugL1: LuauLevel = {
        let (m, j) = LuauLevel.parse([
            "#######",
            "#######",
            "#######",
            "##ooo##",
            "#######",
            "#######",
            "#######",
        ])
        return LuauLevel(id: 1001, mask: m, jelly: j, colors: 4,
                         moves: 15, movesHard: 12,
                         seed: 0xC10D_C1A5_5CE1_ED0F,
                         archetype: "Full Board")
    }()

    /// The Well with light floor jelly — masked-gravity + jelly-in-pocket
    /// probe. Three jelly cells in the well's bottom row: reachable by the
    /// greedy bot within a modest budget.
    static let debugWell: LuauLevel = {
        let (m, j) = LuauLevel.parse([
            "#######",
            "#######",
            "#######",
            "#######",
            "..###..",
            "..###..",
            "..ooo..",
        ])
        // SEED RE-MEASURED 2026-07-31, budget unchanged. The corner-bomb rule
        // pays an L/T one bomb where it accidentally paid two torches before,
        // and the old seed's greedy line lost a free lane to that — one jelly
        // short at any budget tried (the pocket cell simply left the line).
        // Swept 256 seeds with the standalone LuauBot harness: 254 win at
        // attempt 1, so the old seed was a pathological outlier, not a
        // difficulty shift. This one wins attempt 1 in 8 turns and 100/100
        // salted attempts — a real probe of the pocket, with margin.
        return LuauLevel(id: 1002, mask: m, jelly: j, colors: 4,
                         moves: 20, movesHard: 16,
                         seed: 0x11E4_1F8F_3D52_7E9D,
                         archetype: "The Well")
    }()

    /// Full board with two top-row corner jelly cells — the "corner-
    /// jelly" probe. Top-row cells sit in the refill traffic zone, so
    /// the greedy bot (top-left-biased) reaches them within a reasonable
    /// budget. Bottom-row corners are much harder for the greedy policy
    /// (well documented in Stage B calibration notes) and reserved for
    /// production campaign levels where Carson's human calibration sets
    /// the anchor.
    static let debugCorners: LuauLevel = {
        let (m, j) = LuauLevel.parse([
            "o#####o",
            "#######",
            "#######",
            "#######",
            "#######",
            "#######",
            "#######",
        ])
        return LuauLevel(id: 1003, mask: m, jelly: j, colors: 4,
                         moves: 22, movesHard: 17,
                         seed: 0xC0F_FEEC_ABBA_0DDF,
                         archetype: "Full Board")
    }()

    /// The Shelf with a single jelly cell at the top of the staircase,
    /// 6 colors — a "6-color tight" probe.
    static let debugShelf6: LuauLevel = {
        let (m, j) = LuauLevel.parse([
            "#######",
            "###o###",
            "#######",
            "#####..",
            "####...",
            "###....",
            "##.....",
        ])
        return LuauLevel(id: 1004, mask: m, jelly: j, colors: 6,
                         moves: 20, movesHard: 16,
                         seed: 0x5361_6E64_2020_2020,
                         archetype: "The Shelf")
    }()
}
