import Foundation

/// Auto-generated by LevelForge (`campaign build`).
/// Do not hand-edit — regenerate to update.
/// Levels: 188 · ids 13..200
/// Solved by the sand-first bot; budget = min(band, median×1.35).
extension LuauLevels {
    private static let generated0: [LuauLevel] = [
        .init(
            id: 13, mask: 0x1E3C78F1FFFFF,
            jelly: [0,0,0,0,0,0,1,0,0,0,0,1,1,0,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 24, movesHard: 17,
            seed: 0x8D12E6B96EE5423,
            archetype: "The Headland"
        ),
        .init(
            id: 14, mask: 0x1FFFFFFFFFFFF,
            jelly: [0,0,1,1,1,1,1,0,1,1,1,1,1,1,0,0,1,1,1,1,1,0,0,0,1,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 15, movesHard: 11,
            seed: 0xA809A9261739D139,
            archetype: "Full Board"
        ),
        .init(
            id: 15, mask: 0x17EFDFFFFFFFF,
            jelly: [1,1,1,1,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,1,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0],
            colors: 5, moves: 21, movesHard: 15,
            seed: 0x454021DE95834C4D,
            archetype: "The Cove"
        ),
        .init(
            id: 16, mask: 0x1FFFFFFFFDF1C,
            jelly: [0,0,1,0,1,0,0,0,0,0,1,1,0,0,0,0,1,1,0,0,0,1,1,1,1,1,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 15, movesHard: 11,
            seed: 0xE3779B9814CDC862,
            archetype: "The Dune"
        ),
        .init(
            id: 17, mask: 0x3C78F1FFFFFF,
            jelly: [0,0,0,1,1,1,0,0,0,1,1,1,1,1,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 18, movesHard: 13,
            seed: 0x81AF155194184477,
            archetype: "The Headland"
        ),
        .init(
            id: 18, mask: 0x1F7EFDFBFFFFF,
            jelly: [0,1,1,1,1,0,0,1,1,1,1,1,1,0,0,1,1,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 15, movesHard: 11,
            seed: 0x1FE68F0B1362C08C,
            archetype: "The Cove"
        ),
        .init(
            id: 19, mask: 0x71F7FFFFFFBE,
            jelly: [0,1,1,1,1,1,0,0,0,0,1,0,1,0,1,1,0,0,1,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 18, movesHard: 13,
            seed: 0xBE1E08C492AD3CA1,
            archetype: "The Atoll"
        ),
        .init(
            id: 20, mask: 0x1E3C78F1E3FFF,
            jelly: [1,1,1,1,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 21, movesHard: 14,
            seed: 0x5C55827E11F7B8B6,
            archetype: "The Headland"
        ),
        .init(
            id: 21, mask: 0x1F7EFDFFFFFFF,
            jelly: [1,0,0,1,1,1,0,0,1,1,0,1,1,1,1,1,0,1,1,1,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 19, movesHard: 14,
            seed: 0xFB8DFD38924335CC,
            archetype: "The Cove"
        ),
        .init(
            id: 22, mask: 0x1C3870E1FFFFF,
            jelly: [1,1,0,1,1,1,1,0,1,1,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 19, movesHard: 14,
            seed: 0x98C475F1108CB0E0,
            archetype: "The Headland"
        ),
        .init(
            id: 23, mask: 0x1DFBF7EFFFFFF,
            jelly: [1,1,1,1,1,1,0,1,1,1,1,1,0,0,1,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 15, movesHard: 11,
            seed: 0x36FBEFAA8FD72CF5,
            archetype: "The Cove"
        ),
        .init(
            id: 24, mask: 0x1C3870E1FFFF,
            jelly: [0,1,1,1,1,0,1,1,1,1,1,0,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 4, moves: 31, movesHard: 22,
            seed: 0xD7356B670B34AB0D,
            archetype: "The Headland"
        ),
        .init(
            id: 25, mask: 0x78F1EFFFFFFF,
            jelly: [0,0,1,1,1,1,1,0,1,1,1,1,1,1,0,0,1,1,1,1,1,0,0,0,1,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 18, movesHard: 13,
            seed: 0x756CE51F906E2721,
            archetype: "The Well"
        ),
        .init(
            id: 26, mask: 0xE1C7FFFFDC38,
            jelly: [0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0],
            colors: 5, moves: 16, movesHard: 12,
            seed: 0x11A25CD70DB6A134,
            archetype: "The Cross"
        ),
        .init(
            id: 27, mask: 0x1E3C78FFFFFFF,
            jelly: [1,1,1,1,1,0,0,1,1,1,1,1,1,0,1,1,1,1,1,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 18, movesHard: 13,
            seed: 0xB1DBD8928F031F4B,
            archetype: "The Lagoon"
        ),
        .init(
            id: 28, mask: 0x19F3E7CFFFFFF,
            jelly: [0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0],
            colors: 5, moves: 26, movesHard: 22,
            seed: 0x4E11504A0C4B995E,
            archetype: "The Cove"
        ),
        .init(
            id: 29, mask: 0x1E3C78F1E3FFF,
            jelly: [1,1,1,1,1,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1],
            colors: 5, moves: 33, movesHard: 22,
            seed: 0xEC48CA038B961573,
            archetype: "The Headland"
        ),
        .init(
            id: 30, mask: 0x1C79F7FFFFFF,
            jelly: [1,1,1,1,0,1,1,1,1,1,1,1,1,0,1,0,0,0,1,1,0,0,0,1,1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 16, movesHard: 12,
            seed: 0x8C8245BF0CE2938A,
            archetype: "The Shelf"
        ),
        .init(
            id: 31, mask: 0x71F7FFFFDF1C,
            jelly: [0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0],
            colors: 5, moves: 19, movesHard: 14,
            seed: 0x28B7BD768A2B0D9D,
            archetype: "The Atoll"
        ),
        .init(
            id: 32, mask: 0x1F7EFDFBFFFFF,
            jelly: [1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 18, movesHard: 16,
            seed: 0xC8F139320B778BB4,
            archetype: "The Cove"
        ),
        .init(
            id: 33, mask: 0xE1C3871FFFFF,
            jelly: [1,1,1,0,1,1,0,0,0,1,1,1,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 15, movesHard: 11,
            seed: 0x6526B0E988C005C7,
            archetype: "The Well"
        ),
        .init(
            id: 34, mask: 0x1C3870FFFFFF,
            jelly: [0,0,0,1,1,1,0,0,0,1,1,1,1,1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 15, movesHard: 11,
            seed: 0x35E2AA3080A81DC,
            archetype: "The Headland"
        ),
        .init(
            id: 35, mask: 0x70E7FFFFCE1C,
            jelly: [0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,1,1,1,0,1,0,0,1,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 16, movesHard: 12,
            seed: 0xA195A45C8754FDF1,
            archetype: "The Lagoon"
        ),
        .init(
            id: 36, mask: 0x13E7CF9FFFFFF,
            jelly: [1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 21, movesHard: 18,
            seed: 0x41CF201808A17C08,
            archetype: "The Cove"
        ),
        .init(
            id: 37, mask: 0x183878F9FFFFF,
            jelly: [0,0,0,1,1,1,1,0,1,0,1,1,1,1,0,1,1,1,1,1,1,0,0,0,1,1,1,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0],
            colors: 5, moves: 15, movesHard: 13,
            seed: 0xE00699D187EBF81D,
            archetype: "The Shelf"
        ),
        .init(
            id: 38, mask: 0x1FFFFFFFFCE1C,
            jelly: [0,0,1,1,0,0,0,0,0,1,0,1,0,0,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0,1,1,1,1,0,1,0,0,1,0,0,0,0,0,0,0,0],
            colors: 5, moves: 18, movesHard: 16,
            seed: 0x7E3E138B07367432,
            archetype: "The Lagoon"
        ),
        .init(
            id: 39, mask: 0x1C3870E1FFFFF,
            jelly: [1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,1,0,1,0,0,0,0,1,0,1,0,0,0,0,1,0,1,0,0,0,0,0,1,1],
            colors: 5, moves: 24, movesHard: 21,
            seed: 0x1A738B42847EEE45,
            archetype: "The Headland"
        ),
        .init(
            id: 40, mask: 0x1BF7EFDFFFFFF,
            jelly: [0,0,1,1,1,1,1,0,1,1,1,1,1,1,0,0,1,1,1,1,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 18, movesHard: 12,
            seed: 0xB9AC05FD04CA6B5B,
            archetype: "The Cove"
        ),
        .init(
            id: 41, mask: 0xE1C38FFFFFFF,
            jelly: [1,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,1,1,1,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,1,0],
            colors: 5, moves: 20, movesHard: 17,
            seed: 0x56E27EB58313E66F,
            archetype: "The Well"
        ),
        .init(
            id: 42, mask: 0x19F3E7CFFFFFF,
            jelly: [0,1,1,0,0,0,0,0,0,1,1,0,1,0,1,1,1,1,1,1,1,0,0,0,0,0,1,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 21, movesHard: 18,
            seed: 0xF519F86F025E6284,
            archetype: "The Cove"
        ),
        .init(
            id: 43, mask: 0x70E1CFFFFFFF,
            jelly: [1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,1,1,1,0,0,0,1,1,0,0,0,0,1,0,1,0,0,0,0,1,0,1,0,0],
            colors: 5, moves: 22, movesHard: 19,
            seed: 0x9351722881A8DE99,
            archetype: "The Well"
        ),
        .init(
            id: 44, mask: 0x71F7FFFFFFBE,
            jelly: [0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,1,1,1,1,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0],
            colors: 5, moves: 16, movesHard: 12,
            seed: 0x3188EBE200F35AAE,
            archetype: "The Atoll"
        ),
        .init(
            id: 45, mask: 0x1E7CF9FFFFFFF,
            jelly: [1,1,1,1,1,1,1,1,0,0,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,1,1],
            colors: 5, moves: 22, movesHard: 19,
            seed: 0xCFC0659B803DD6C3,
            archetype: "The Cove"
        ),
        .init(
            id: 46, mask: 0x70E1C39FFFFF,
            jelly: [0,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,1,1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 16, movesHard: 14,
            seed: 0x6FF9E157018A54DA,
            archetype: "The Well"
        ),
        .init(
            id: 47, mask: 0x17EFDFBFFFFFF,
            jelly: [1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,0,1,0,1,1,0,1,1,1,1,1,0,0,0,1,1,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 21, movesHard: 18,
            seed: 0xE315B1080D4D0EF,
            archetype: "The Cove"
        ),
        .init(
            id: 48, mask: 0xF1E3C79FFFFF,
            jelly: [1,1,1,0,0,0,0,1,1,1,1,1,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 22, movesHard: 16,
            seed: 0xAA66D2C7FE1D4B02,
            archetype: "The Well"
        ),
        .init(
            id: 49, mask: 0x70E7FFFFCE1C,
            jelly: [0,0,1,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,0,0,0,1,0,1,1,1,0,0,0,0,0,0,0,0,0,2,2,0,0,0],
            colors: 5, moves: 28, movesHard: 24,
            seed: 0x489E4C817D67C717,
            archetype: "The Lagoon"
        ),
        .init(
            id: 50, mask: 0x70E1C39FFFFF,
            jelly: [2,1,1,1,0,1,1,1,1,1,0,1,0,0,0,0,1,1,1,0,0,0,0,2,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 20, movesHard: 17,
            seed: 0xE7D6C73BFDB3442D,
            archetype: "The Well"
        ),
        .init(
            id: 51, mask: 0xE1C7FFFFDC38,
            jelly: [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,1,1,1,1,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,2,1,2,0],
            colors: 5, moves: 22, movesHard: 19,
            seed: 0x850D3FF47BFCBF41,
            archetype: "The Cross"
        ),
        .init(
            id: 52, mask: 0x41871E7FFFF,
            jelly: [2,1,1,1,1,1,0,1,1,1,1,1,0,0,2,1,1,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 20, movesHard: 17,
            seed: 0x2546BBAFFD493D58,
            archetype: "The Shelf"
        ),
        .init(
            id: 53, mask: 0xF1E3CFFFFFFF,
            jelly: [0,0,1,1,1,1,0,1,1,1,1,0,1,1,2,0,1,1,1,0,2,0,0,1,1,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 20, movesHard: 17,
            seed: 0xC27D34687B92B86C,
            archetype: "The Well"
        ),
        .init(
            id: 54, mask: 0x1FFFFFFFFCE1C,
            jelly: [0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,1,1,0,1,1,1,1,1,1,0,0,0,1,1,1,1,0,0,0,0,1,1,1,0,0,0,0,0,2,2],
            colors: 5, moves: 23, movesHard: 20,
            seed: 0x60B4AE21FADD3481,
            archetype: "The Lagoon"
        ),
        .init(
            id: 55, mask: 0x1FFFFFFFFF3C3,
            jelly: [1,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,1,1,1,0,0,0,0,1,0,0,1,0,0,0,0,2,1,0,1,1,1,0,0,0,2,1,0,2,0],
            colors: 5, moves: 24, movesHard: 21,
            seed: 0xFDEB26DA7926AF95,
            archetype: "The Dune"
        ),
        .init(
            id: 56, mask: 0x1C79F7FFFFFF,
            jelly: [1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,1,1,0,1,1,0,1,0,0,0,1,0,1,1,0,0,0,2,1,2,0,0,0,0],
            colors: 5, moves: 28, movesHard: 24,
            seed: 0x9C22A093F8712BAA,
            archetype: "The Shelf"
        ),
        .init(
            id: 57, mask: 0x1FFFFFFFFF9E1,
            jelly: [2,0,0,0,0,0,0,1,1,0,0,1,0,0,1,1,1,1,1,1,0,2,1,1,1,1,0,0,2,1,1,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 30, movesHard: 26,
            seed: 0x3B5B1B4E78BCA8C0,
            archetype: "The Dune"
        ),
        .init(
            id: 58, mask: 0x1C3C7CFDFFFFF,
            jelly: [0,0,1,1,1,1,0,2,1,1,1,1,1,2,0,1,1,1,1,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 20, movesHard: 17,
            seed: 0xD9929507F80724D5,
            archetype: "The Shelf"
        ),
        .init(
            id: 59, mask: 0xF1E3C79FFFFF,
            jelly: [2,1,1,1,1,1,2,0,1,1,0,0,0,0,0,0,1,1,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 21, movesHard: 18,
            seed: 0x76C90DC076509FE9,
            archetype: "The Well"
        ),
        .init(
            id: 60, mask: 0x103070F1F3FFF,
            jelly: [1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,2,1,1,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 26, movesHard: 22,
            seed: 0x1702897BF79D1E00,
            archetype: "The Shelf"
        ),
        .init(
            id: 61, mask: 0x1FFFFF1C38204,
            jelly: [0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1,1,1,1,1,1,1,1,2,0,0,1,0,0,0,0,0,0,1,0],
            colors: 5, moves: 23, movesHard: 20,
            seed: 0xB439023475E69914,
            archetype: "The Pyramid"
        ),
        .init(
            id: 62, mask: 0x103070F1F3FFF,
            jelly: [1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,2,1,1,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 26, movesHard: 22,
            seed: 0x53717CEEF632162A,
            archetype: "The Shelf"
        ),
    ]
    private static let generated1: [LuauLevel] = [
        .init(
            id: 63, mask: 0x78F1E3DFFFFF,
            jelly: [0,0,0,0,1,1,0,0,0,0,0,0,0,0,2,1,1,1,1,1,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,2,1,1,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 21, movesHard: 18,
            seed: 0xEFA6F4A6737A903D,
            archetype: "The Well"
        ),
        .init(
            id: 64, mask: 0x1FFFFF70E0810,
            jelly: [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,1,0,1,0,1,1,1,1,0,1,1,1,1,0,0,2,1,0,2,1,0,0,0,0,0],
            colors: 5, moves: 24, movesHard: 21,
            seed: 0x8FE07061F4C70E54,
            archetype: "The Pyramid"
        ),
        .init(
            id: 65, mask: 0x70E7FFFFCE1C,
            jelly: [0,0,2,1,2,0,0,0,0,1,0,1,0,0,0,1,0,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 18, movesHard: 16,
            seed: 0x2E17EA1B74118A69,
            archetype: "The Lagoon"
        ),
        .init(
            id: 66, mask: 0x1071F7FFFFFF,
            jelly: [0,1,0,0,0,0,0,0,0,0,1,1,1,0,1,0,0,0,1,1,1,1,0,0,1,0,1,0,2,0,0,1,1,0,0,0,2,1,2,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 23, movesHard: 22,
            seed: 0xCA4D61D2F15A047C,
            archetype: "The Funnel"
        ),
        .init(
            id: 67, mask: 0xA952A54ABFFF,
            jelly: [1,1,0,0,1,0,0,2,1,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 4, moves: 21, movesHard: 18,
            seed: 0x6884DB8C70A48091,
            archetype: "The Jetty"
        ),
        .init(
            id: 68, mask: 0x3870EFFFFFFF,
            jelly: [0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,1,1,1,0,0,1,1,1,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,2,0,2,0,0,0],
            colors: 5, moves: 28, movesHard: 24,
            seed: 0x6BC5545EFEEFCA6,
            archetype: "The Well"
        ),
        .init(
            id: 69, mask: 0xD9B366DFFFFF,
            jelly: [1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0,1,0,0,0,1,0,1,1,0,0,1,1,0,1,0,0,0,0,2,0,2,0,0],
            colors: 5, moves: 46, movesHard: 39,
            seed: 0xA4F3CEFF6F3978BB,
            archetype: "The Jetty"
        ),
        .init(
            id: 70, mask: 0x1BF7EFDFBF7EF,
            jelly: [1,1,1,1,0,0,0,1,1,1,1,0,0,0,1,1,1,1,0,0,0,1,1,1,1,0,0,0,1,1,1,1,0,0,0,2,1,1,1,0,0,0,0,2,0,0,0,0,0],
            colors: 5, moves: 21, movesHard: 18,
            seed: 0x452D4ABAF085F6D2,
            archetype: "The Channel"
        ),
        .init(
            id: 71, mask: 0x70E1CFFFFFFF,
            jelly: [0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,1,1,0,1,1,0,1,1,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,2,0,2,0,0],
            colors: 5, moves: 24, movesHard: 21,
            seed: 0xE162C2726DCE70E5,
            archetype: "The Well"
        ),
        .init(
            id: 72, mask: 0x156AD5ABFFFFF,
            jelly: [2,0,0,1,1,0,2,1,1,0,1,1,0,1,2,1,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 19, movesHard: 19,
            seed: 0x7F9A3C2BED18ECFA,
            archetype: "The Jetty"
        ),
        .init(
            id: 73, mask: 0x20E3EFFFDF1C,
            jelly: [0,0,0,1,2,0,0,0,2,1,1,1,2,0,1,1,1,1,0,1,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 22, movesHard: 19,
            seed: 0x1ED2B6E66D646A10,
            archetype: "The Atoll"
        ),
        .init(
            id: 74, mask: 0x183878F9FFFFF,
            jelly: [2,1,1,0,0,1,0,2,1,0,1,1,1,2,0,0,1,1,1,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 24, movesHard: 21,
            seed: 0xBC092F9EEBADE524,
            archetype: "The Shelf"
        ),
        .init(
            id: 75, mask: 0x17EFDFFFFFFFF,
            jelly: [2,1,1,1,1,0,0,2,1,1,1,1,1,0,2,1,1,1,1,0,0,0,0,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 6, moves: 22, movesHard: 19,
            seed: 0x5A40A9586AF86139,
            archetype: "The Cove"
        ),
        .init(
            id: 76, mask: 0x1BF7EFDFBF7EF,
            jelly: [2,1,1,2,0,0,2,0,1,1,1,0,1,0,1,1,0,0,0,1,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 4, moves: 29, movesHard: 19,
            seed: 0xF8782312E453DD4F,
            archetype: "The Channel"
        ),
        .init(
            id: 77, mask: 0x1E7CF9F3FFFFF,
            jelly: [2,1,1,0,1,1,2,0,1,0,0,1,1,1,2,0,2,1,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 23, movesHard: 20,
            seed: 0x96AF9CCB698D5963,
            archetype: "The Cove"
        ),
        .init(
            id: 78, mask: 0x1FFFFFFFFFFFF,
            jelly: [1,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,1,1,0,1,1,2,0,1,0,0,0,2,0,0,1,1,1,0,2,0,0,2,0,0,0,2],
            colors: 6, moves: 39, movesHard: 33,
            seed: 0x34E71684E8D7D578,
            archetype: "Full Board"
        ),
        .init(
            id: 79, mask: 0x13E7CF9FFFFFF,
            jelly: [0,1,1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,2,2,0,0,0,1,2,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 20, movesHard: 17,
            seed: 0xD41F913F6923528E,
            archetype: "The Cove"
        ),
        .init(
            id: 80, mask: 0xF1E3C79FFFFF,
            jelly: [1,0,0,0,0,0,1,0,0,0,0,0,0,1,2,1,0,0,0,0,2,0,0,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,1,1,2,0,0,0,2,0,0,0,0],
            colors: 5, moves: 33, movesHard: 28,
            seed: 0x715609F7E76CCDA2,
            archetype: "The Well"
        ),
        .init(
            id: 81, mask: 0x1C3870E1C3FFF,
            jelly: [0,0,0,0,0,0,1,0,1,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,2,0,0,0,0,0,0,2,0,2],
            colors: 5, moves: 26, movesHard: 22,
            seed: 0xF8D83B166B749B7,
            archetype: "The Headland"
        ),
        .init(
            id: 82, mask: 0x1071F7FFFFFF,
            jelly: [2,1,1,1,0,1,0,2,1,0,1,1,1,2,0,1,1,1,0,0,0,0,0,2,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 22, movesHard: 19,
            seed: 0xAEC5FE6BE702C6CD,
            archetype: "The Funnel"
        ),
        .init(
            id: 83, mask: 0x1C3870E1FFFFF,
            jelly: [0,1,1,1,1,0,2,1,1,1,1,1,0,1,0,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 21, movesHard: 18,
            seed: 0x4BFC7724654C41E1,
            archetype: "The Headland"
        ),
        .init(
            id: 84, mask: 0x2041C38FBFFF,
            jelly: [0,0,0,1,1,1,2,0,1,1,1,0,1,2,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 28, movesHard: 24,
            seed: 0xEB34F1DEE597BEF7,
            archetype: "The Funnel"
        ),
        .init(
            id: 85, mask: 0x1E3C78FFFFFFF,
            jelly: [1,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,0,1,0,1,1,1,0,0,1,0,0,0,2,1,0,2,0,0,0,0,1,1,0,0,0,0,0,2,2,0],
            colors: 5, moves: 24, movesHard: 21,
            seed: 0x886B6A9763E13A0B,
            archetype: "The Lagoon"
        ),
        .init(
            id: 86, mask: 0xC38F3FFFFFF,
            jelly: [1,0,0,0,0,0,0,1,0,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,1,1,0,0,0,0,0,2,0,0,0,0,1,2,0,0,0,0,2,2,0,0,0,0,0],
            colors: 5, moves: 41, movesHard: 40,
            seed: 0x26A2E450E32BB620,
            archetype: "The Shelf"
        ),
        .init(
            id: 87, mask: 0xE1C7FFFFDC38,
            jelly: [0,0,0,1,1,0,0,0,0,0,1,0,0,0,1,1,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,2,1,2,0,0,0,0,0,0,2,0],
            colors: 5, moves: 27, movesHard: 23,
            seed: 0xC4DA5E0A62763235,
            archetype: "The Cross"
        ),
        .init(
            id: 88, mask: 0x1DFBF7EFDFBF7,
            jelly: [1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,1,1,0,0,1,1,0,1,1,1,2,1,1,0,1,0,0,2,0,2,0,0,2,2],
            colors: 5, moves: 39, movesHard: 38,
            seed: 0x6311D7C3E1C0AE4A,
            archetype: "The Channel"
        ),
        .init(
            id: 89, mask: 0x1264C99327FFF,
            jelly: [2,0,0,1,0,0,2,2,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 4, moves: 15, movesHard: 13,
            seed: 0x34B537F630D2C61,
            archetype: "The Jetty"
        ),
        .init(
            id: 90, mask: 0x3870E1DFFFFF,
            jelly: [1,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,1,0,0,1,1,1,0,0,0,0,0,1,0,0,0,0,0,2,0,1,0,0,0,0,2,2,2,0,0,0],
            colors: 5, moves: 24, movesHard: 23,
            seed: 0x9F80CB36E055A674,
            archetype: "The Well"
        ),
        .init(
            id: 91, mask: 0x73FFFFE70E1C,
            jelly: [0,0,2,1,2,0,0,0,0,1,1,1,0,0,0,0,1,1,1,0,0,0,1,1,1,1,1,1,0,0,1,1,1,1,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 16, movesHard: 14,
            seed: 0x3FBA46F261A2248B,
            archetype: "The Cross"
        ),
        .init(
            id: 92, mask: 0xE1C3871FFFFF,
            jelly: [1,0,0,0,0,0,1,1,0,0,0,0,0,1,2,1,1,0,0,0,1,0,0,0,1,1,0,0,0,0,0,0,1,1,0,0,0,0,2,0,2,0,0,0,0,0,0,2,0],
            colors: 5, moves: 28, movesHard: 27,
            seed: 0xDBEFBEA9DEEA9E9E,
            archetype: "The Well"
        ),
        .init(
            id: 93, mask: 0x1FFFFFFFFF3C3,
            jelly: [2,2,0,0,0,0,0,0,1,0,0,0,2,2,0,1,1,1,1,1,0,0,0,1,0,1,1,0,0,0,0,0,1,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 36, movesHard: 31,
            seed: 0x7A2738635E351AB3,
            archetype: "The Dune"
        ),
        .init(
            id: 94, mask: 0xA952A55FFFFF,
            jelly: [2,0,1,1,1,0,2,0,1,1,0,0,0,1,2,1,1,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 21, movesHard: 21,
            seed: 0x185EB21CDD7F96C8,
            archetype: "The Jetty"
        ),
        .init(
            id: 95, mask: 0x1FFFFFFFFCE1C,
            jelly: [0,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,1,1,1,1,1,0,0,2,2,2,2,0,1,0],
            colors: 5, moves: 20, movesHard: 17,
            seed: 0xB6962BD65CCA12DD,
            archetype: "The Lagoon"
        ),
        .init(
            id: 96, mask: 0x1C3C7CFDFFFFF,
            jelly: [0,0,1,0,0,0,0,0,1,0,0,1,0,1,1,1,1,0,1,0,0,0,1,0,0,1,1,0,0,0,2,0,0,0,1,0,0,0,2,0,1,0,0,0,0,0,2,2,2],
            colors: 6, moves: 41, movesHard: 40,
            seed: 0x54CDA58FDC148EF2,
            archetype: "The Shelf"
        ),
        .init(
            id: 97, mask: 0x1FFFFFFFFF3C3,
            jelly: [0,0,0,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,1,0,2,1,0,1,1,1,2,0,2,0,0,1,1,2],
            colors: 6, moves: 41, movesHard: 35,
            seed: 0xF3051F495B5F0B07,
            archetype: "The Dune"
        ),
        .init(
            id: 98, mask: 0xF1E3C79FFFFF,
            jelly: [2,1,1,1,1,0,0,1,0,1,1,0,0,1,0,2,1,1,1,1,0,0,0,0,1,0,0,0,0,0,0,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 20, movesHard: 17,
            seed: 0x923D9A03DBAA881D,
            archetype: "The Well"
        ),
        .init(
            id: 99, mask: 0x1FFFFF3870408,
            jelly: [0,0,0,2,0,0,0,0,0,0,2,0,0,0,0,0,1,0,1,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,1,1,0,1,1,0,0,0,0,0,2,0,2,1,0],
            colors: 5, moves: 19, movesHard: 19,
            seed: 0x2F7412BC59F40331,
            archetype: "The Pyramid"
        ),
        .init(
            id: 100, mask: 0x3870E1DFFFFF,
            jelly: [1,0,0,0,0,0,0,1,0,0,0,0,0,1,2,0,0,0,1,1,1,0,1,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,2,0,0,0,0,0,2,0,0,0,0],
            colors: 5, moves: 28, movesHard: 24,
            seed: 0xCDAB8C75D93E7F46,
            archetype: "The Well"
        ),
        .init(
            id: 101, mask: 0x1C79F7FFFFFF,
            jelly: [0,1,1,0,1,1,0,1,0,0,0,1,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,2,1,1,0,0,0,0,0,0,0,0,0,0,0,2,2,2,0,0,0,0],
            colors: 6, moves: 44, movesHard: 37,
            seed: 0x6BE3062F5888FB5B,
            archetype: "The Shelf"
        ),
        .init(
            id: 102, mask: 0x1FFFFF1C38204,
            jelly: [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,1,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,2,2,2,2,1,1,1],
            colors: 5, moves: 19, movesHard: 19,
            seed: 0xA1A7FE8D7D37770,
            archetype: "The Pyramid"
        ),
        .init(
            id: 103, mask: 0xD9B366DFFFFF,
            jelly: [0,0,1,0,1,0,0,0,1,0,0,1,0,0,2,1,1,1,1,1,2,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,2,2,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 34, movesHard: 29,
            seed: 0xA851F9A2571DF385,
            archetype: "The Jetty"
        ),
        .init(
            id: 104, mask: 0x1C3C7CFDFFFFF,
            jelly: [1,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,1,1,0,0,0,1,0,0,2,0,0,0,2,1,1,2,0,0,0,0,2,0,0],
            colors: 6, moves: 50, movesHard: 43,
            seed: 0x488B755DD86A719C,
            archetype: "The Shelf"
        ),
        .init(
            id: 105, mask: 0x4083871F3FFF,
            jelly: [1,1,1,1,1,0,0,1,0,0,0,0,0,1,0,0,2,0,0,0,0,0,0,0,1,0,1,0,0,0,0,2,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 27, movesHard: 26,
            seed: 0xE4C0ED1555B2EBAF,
            archetype: "The Funnel"
        ),
        .init(
            id: 106, mask: 0xD9B366CDBFFF,
            jelly: [2,1,1,0,1,0,1,2,0,1,1,1,0,0,0,1,1,0,0,1,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 4, moves: 20, movesHard: 17,
            seed: 0x82F866CED4FD67C4,
            archetype: "The Jetty"
        ),
        .init(
            id: 107, mask: 0x1FFFFFFFF1C10,
            jelly: [0,0,0,0,2,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,1,0,0,0,1,0,1,0,0,1,1,0,0,2,2,1,0,0,0,2,0],
            colors: 6, moves: 44, movesHard: 37,
            seed: 0x212FE0885447E3D9,
            archetype: "The Pyramid"
        ),
        .init(
            id: 108, mask: 0x156AD5AB57FFF,
            jelly: [2,1,0,1,0,1,2,2,2,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 4, moves: 18, movesHard: 18,
            seed: 0xC1695C43D59461F0,
            archetype: "The Jetty"
        ),
        .init(
            id: 109, mask: 0x1FFFFFFEF8E08,
            jelly: [0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,1,0,0,1,1,0,0,0,0,0,1,1,1,0,1,2,2,2,0,2,1,2],
            colors: 5, moves: 23, movesHard: 22,
            seed: 0x5D9ED3FB52DCDC03,
            archetype: "The Pyramid"
        ),
        .init(
            id: 110, mask: 0x20E3EFFFFFFF,
            jelly: [0,1,1,0,0,0,2,1,0,0,0,0,0,1,1,0,0,0,0,0,1,2,1,1,1,0,0,2,0,0,1,1,0,2,0,0,0,2,2,0,0,0,0,0,0,0,0,0,0],
            colors: 6, moves: 40, movesHard: 39,
            seed: 0xFBD64DB4D2275818,
            archetype: "The Funnel"
        ),
        .init(
            id: 111, mask: 0x156AD5AB57FFF,
            jelly: [2,2,0,1,1,1,2,0,0,1,2,0,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 4, moves: 16, movesHard: 16,
            seed: 0x9C0FC9705373D62F,
            archetype: "The Jetty"
        ),
        .init(
            id: 112, mask: 0x1FFFFFFFF1C10,
            jelly: [0,0,0,0,2,0,0,0,0,0,2,1,2,0,0,0,2,1,1,1,2,0,0,0,1,1,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 6, moves: 29, movesHard: 25,
            seed: 0x38454127D0BC5042,
            archetype: "The Pyramid"
        ),
    ]
    private static let generated2: [LuauLevel] = [
        .init(
            id: 113, mask: 0x1071F7FFFFFF,
            jelly: [0,1,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,2,1,0,1,1,1,2,0,2,0,1,1,2,0,0,0,2,1,2,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 26, movesHard: 25,
            seed: 0xD67CBAE15006CC57,
            archetype: "The Funnel"
        ),
        .init(
            id: 114, mask: 0xA952A54ABFFF,
            jelly: [2,0,0,1,1,0,2,2,0,2,1,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 4, moves: 25, movesHard: 24,
            seed: 0x74B4349ACF51486C,
            archetype: "The Jetty"
        ),
        .init(
            id: 115, mask: 0x1FFFFFFE7C704,
            jelly: [0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,1,0,1,1,0,0,1,2,2,2,2,2,1,2],
            colors: 5, moves: 21, movesHard: 21,
            seed: 0x12EBAE544E9BC481,
            archetype: "The Pyramid"
        ),
        .init(
            id: 116, mask: 0x1264C99327FFF,
            jelly: [2,1,0,1,0,0,2,2,2,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 4, moves: 20, movesHard: 17,
            seed: 0xB123280DCDE64096,
            archetype: "The Jetty"
        ),
        .init(
            id: 117, mask: 0x4083871F3FFF,
            jelly: [1,1,1,1,0,0,1,2,1,0,0,0,0,1,0,0,2,0,0,0,0,0,0,0,2,1,2,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 36, movesHard: 35,
            seed: 0x4F5AA1C74D30BCAB,
            archetype: "The Funnel"
        ),
        .init(
            id: 118, mask: 0xA952A55FFFFF,
            jelly: [2,1,1,0,1,1,2,0,1,1,1,0,0,0,2,1,0,1,2,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 26, movesHard: 25,
            seed: 0xED921B80CC7B38C0,
            archetype: "The Jetty"
        ),
        .init(
            id: 119, mask: 0x2041C38FBFFF,
            jelly: [0,1,1,0,1,1,1,2,0,0,0,0,0,2,0,0,0,0,0,2,0,0,0,2,1,1,0,0,0,0,0,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 32, movesHard: 31,
            seed: 0x8BC9953A4BC5B4D5,
            archetype: "The Funnel"
        ),
        .init(
            id: 120, mask: 0x1FFFFF1C38204,
            jelly: [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,1,1,0,0,0,0,1,2,1,1,1,1,0,0,2,1,1,1,1,0,0,0,2,1,1,0],
            colors: 5, moves: 18, movesHard: 16,
            seed: 0x2C0310F5CD1232EC,
            archetype: "The Pyramid"
        ),
        .init(
            id: 121, mask: 0xE1C38FFFFFFF,
            jelly: [0,0,0,2,1,0,0,2,1,1,1,1,1,2,0,1,0,1,1,1,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 20, movesHard: 17,
            seed: 0xC83888AD4A5AACFF,
            archetype: "The Well"
        ),
        .init(
            id: 122, mask: 0x1FFFFFFFFCE1C,
            jelly: [0,0,1,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,1,0,1,0,1,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,1,0,0,2,0,0,2,2,2],
            colors: 5, moves: 28, movesHard: 24,
            seed: 0x66700266C9A52914,
            archetype: "The Lagoon"
        ),
        .init(
            id: 123, mask: 0x1FFFFFFFFFFFF,
            jelly: [2,1,1,1,1,1,2,2,1,1,1,0,1,1,0,1,1,1,1,1,0,0,0,1,1,1,0,0,0,0,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 23, movesHard: 20,
            seed: 0x5A87D2149F0A62A,
            archetype: "Full Board"
        ),
        .init(
            id: 124, mask: 0xF1E3CFFFFFFF,
            jelly: [0,0,1,0,0,0,0,1,1,1,0,0,1,1,0,0,0,1,0,0,0,2,2,1,1,1,1,2,0,0,0,1,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 20, movesHard: 17,
            seed: 0xA2DEF5D9C83A213E,
            archetype: "The Well"
        ),
        .init(
            id: 125, mask: 0x3C78F1E3FFFF,
            jelly: [1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,2,1,1,1,0,0,0,0,0,1,2,0,0,0,0,2,0,0,0,0,0],
            colors: 5, moves: 21, movesHard: 18,
            seed: 0x41166F9347849D53,
            archetype: "The Headland"
        ),
        .init(
            id: 126, mask: 0x73FFFFE70E1C,
            jelly: [0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,1,0,0,2,1,0,2,0,1,0,0,0,0,2,0,0,0],
            colors: 5, moves: 23, movesHard: 20,
            seed: 0xDF4DE94CC6CF1968,
            archetype: "The Cross"
        ),
        .init(
            id: 127, mask: 0x41871E7FFFF,
            jelly: [1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,1,0,1,0,0,0,0,1,1,2,0,0,0,0,2,2,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 34, movesHard: 29,
            seed: 0x7D8563064619957D,
            archetype: "The Shelf"
        ),
        .init(
            id: 128, mask: 0x70E1C39FFFFF,
            jelly: [0,1,0,1,0,1,0,0,1,1,0,1,1,0,0,0,0,1,0,0,0,0,0,2,1,1,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,2,0,0,0],
            colors: 5, moves: 21, movesHard: 18,
            seed: 0x1BBCDCBFC5641192,
            archetype: "The Well"
        ),
        .init(
            id: 129, mask: 0x1EFDFBF7FFFFF,
            jelly: [0,1,1,1,0,0,0,1,0,0,0,0,0,0,1,1,1,1,1,1,1,0,0,0,1,0,0,0,0,0,0,2,0,1,0,0,0,0,0,0,0,2,0,2,0,2,0,0,0],
            colors: 5, moves: 40, movesHard: 34,
            seed: 0xB9F4567944AE8DA7,
            archetype: "The Cove"
        ),
        .init(
            id: 130, mask: 0x3870E1DFFFFF,
            jelly: [1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,1,1,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,2,0,1,0,0,0,0,2,2,0,0,0,0],
            colors: 5, moves: 30, movesHard: 26,
            seed: 0x582BD032C3F909BC,
            archetype: "The Well"
        ),
        .init(
            id: 131, mask: 0x13E7CF9FFFFFF,
            jelly: [0,0,0,0,0,0,1,1,0,0,0,0,0,1,1,0,0,0,1,1,1,0,1,0,1,0,0,0,0,0,1,2,0,0,0,2,1,1,2,0,0,0,0,0,0,2,0,0,0],
            colors: 5, moves: 29, movesHard: 25,
            seed: 0xF66349EC434385D1,
            archetype: "The Cove"
        ),
        .init(
            id: 132, mask: 0x71F7FFFFDF1C,
            jelly: [0,0,2,0,2,0,0,0,0,1,1,1,2,0,2,1,0,0,0,1,0,1,1,1,1,1,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 22, movesHard: 19,
            seed: 0x959BC4A6C38F02E7,
            archetype: "The Atoll"
        ),
        .init(
            id: 133, mask: 0x1FFFFF70E0810,
            jelly: [0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,2,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,1,0,0,0,0,1,1,2,0,1,0,0,0,2],
            colors: 5, moves: 29, movesHard: 25,
            seed: 0x32D23D5F41D87DFB,
            archetype: "The Pyramid"
        ),
        .init(
            id: 134, mask: 0x1EFDFBF7EFDFB,
            jelly: [2,2,0,2,1,0,1,1,1,0,1,1,1,0,1,1,0,0,0,1,1,2,2,0,2,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 4, moves: 38, movesHard: 32,
            seed: 0xD109B719BB33FA11,
            archetype: "The Channel"
        ),
        .init(
            id: 135, mask: 0x156AD5AB57FFF,
            jelly: [0,2,0,1,1,1,0,2,2,1,2,1,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 4, moves: 16, movesHard: 14,
            seed: 0x714332D4426F7827,
            archetype: "The Jetty"
        ),
        .init(
            id: 136, mask: 0x103070F1F3FFF,
            jelly: [1,1,0,1,1,0,0,1,1,0,0,0,0,0,0,0,2,0,0,0,1,0,0,0,2,1,0,0,0,0,0,0,2,1,2,0,0,0,0,0,2,0,0,0,0,0,0,0,0],
            colors: 5, moves: 35, movesHard: 34,
            seed: 0xD78AA8BBFB7F23A,
            archetype: "The Shelf"
        ),
        .init(
            id: 137, mask: 0x1E3C78FFFFFFF,
            jelly: [2,2,2,1,1,1,0,2,1,1,1,1,0,0,2,1,1,1,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 6, moves: 34, movesHard: 29,
            seed: 0xABB024453F026E4F,
            archetype: "The Lagoon"
        ),
        .init(
            id: 138, mask: 0x183878F9FFFFF,
            jelly: [1,1,0,0,0,0,1,1,0,0,0,0,0,1,2,0,0,0,0,0,0,0,0,2,1,0,1,0,0,0,0,2,1,1,0,0,0,0,0,2,1,2,0,0,0,0,0,2,0],
            colors: 5, moves: 39, movesHard: 38,
            seed: 0x49E79DFEBE4CEA64,
            archetype: "The Shelf"
        ),
        .init(
            id: 139, mask: 0x20E3EFFFFFFF,
            jelly: [2,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,1,1,0,0,0,2,2,1,1,2,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0],
            colors: 6, moves: 38, movesHard: 32,
            seed: 0xE81F17B83D976679,
            archetype: "The Funnel"
        ),
        .init(
            id: 140, mask: 0x1C3C7CFDFFFFF,
            jelly: [1,0,0,0,0,0,1,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,2,1,1,0,0,1,0,0,2,0,1,1,1,0,0,0,2,0,1,2,0,0,0,0,0,2,2],
            colors: 6, moves: 48, movesHard: 46,
            seed: 0x86569171BCE1E28E,
            archetype: "The Shelf"
        ),
        .init(
            id: 141, mask: 0x1264C99327FFF,
            jelly: [0,1,1,1,1,1,2,0,0,0,1,2,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 4, moves: 14, movesHard: 12,
            seed: 0x26900D2D3E2E60A5,
            archetype: "The Jetty"
        ),
        .init(
            id: 142, mask: 0xE1C7FFFFDC38,
            jelly: [0,0,0,1,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,2,0,1,1,1,1,0,0,0,0,2,1,2,0,0,0,0,2,2,0,0],
            colors: 5, moves: 28, movesHard: 27,
            seed: 0xC2C584E4BB76DAB8,
            archetype: "The Cross"
        ),
        .init(
            id: 143, mask: 0x1264C993FFFFF,
            jelly: [2,1,1,1,0,0,0,1,1,1,1,1,1,0,2,2,2,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 20, movesHard: 17,
            seed: 0x61FDFF9F3BC257CE,
            archetype: "The Jetty"
        ),
        .init(
            id: 144, mask: 0x3870E1DFFFFF,
            jelly: [0,0,0,0,0,0,1,1,0,0,0,0,0,1,2,0,0,0,1,1,2,0,1,1,1,0,0,0,0,1,0,0,0,0,0,0,2,1,0,0,0,0,0,2,0,2,0,0,0],
            colors: 5, moves: 32, movesHard: 31,
            seed: 0xFF347857BA0BD2E2,
            archetype: "The Well"
        ),
        .init(
            id: 145, mask: 0x1FFFFF1C38204,
            jelly: [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,1,1,0,1,0,0,0,0,0,1,2,2,2,2,1,1,2],
            colors: 5, moves: 24, movesHard: 23,
            seed: 0x9D6BF21139564EF7,
            archetype: "The Pyramid"
        ),
        .init(
            id: 146, mask: 0xD9B366DFFFFF,
            jelly: [1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,1,1,0,1,1,0,0,1,1,0,0,1,0,0,2,0,0,2,2,0,0,2,2,0,2,0,0],
            colors: 5, moves: 50, movesHard: 50,
            seed: 0x3DA56DCCBAA2CD0E,
            archetype: "The Jetty"
        ),
        .init(
            id: 147, mask: 0x1EFDFBF7EFDFB,
            jelly: [1,0,0,1,0,1,0,1,0,0,0,0,0,0,0,1,0,1,1,0,1,0,0,0,1,0,0,0,0,2,0,1,1,0,1,0,0,0,0,0,1,0,2,2,0,2,2,2,2],
            colors: 5, moves: 49, movesHard: 47,
            seed: 0xDBDCE78639ED4923,
            archetype: "The Channel"
        ),
        .init(
            id: 148, mask: 0x1FFFFFFEF8E08,
            jelly: [0,0,0,2,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,1,0,0,0,1,1,1,0,2,1,2,2,2,1,2],
            colors: 6, moves: 45, movesHard: 43,
            seed: 0x78125F3DB735C336,
            archetype: "The Pyramid"
        ),
        .init(
            id: 149, mask: 0x156AD5AB57FFF,
            jelly: [2,0,1,0,1,0,2,2,2,1,2,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 4, moves: 17, movesHard: 15,
            seed: 0x184BDAF93882414D,
            archetype: "The Jetty"
        ),
        .init(
            id: 150, mask: 0x20E3EFFFFFFF,
            jelly: [1,0,0,0,0,0,1,1,0,0,0,0,0,1,1,0,0,0,0,0,1,2,0,1,0,1,1,2,0,2,1,0,0,2,0,0,0,2,1,2,0,0,0,0,0,0,0,0,0],
            colors: 6, moves: 37, movesHard: 36,
            seed: 0xB48152B0B5CABB60,
            archetype: "The Funnel"
        ),
        .init(
            id: 151, mask: 0x1264C99327FFF,
            jelly: [2,1,1,0,1,1,2,2,2,2,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 4, moves: 16, movesHard: 16,
            seed: 0x54BACE6C37173977,
            archetype: "The Jetty"
        ),
        .init(
            id: 152, mask: 0x1FFFFF3870408,
            jelly: [0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,1,0,0,1,0,0,1,0,0,0,1,0,0,0,2,1,2,0,2,1,2],
            colors: 5, moves: 27, movesHard: 26,
            seed: 0xF0F04623B45FB38A,
            archetype: "The Pyramid"
        ),
        .init(
            id: 153, mask: 0x1DFBF7EFDFBF7,
            jelly: [1,0,1,0,0,0,1,1,0,1,0,1,0,0,1,0,0,0,0,0,1,0,0,2,0,1,1,1,0,0,0,0,0,1,0,2,0,0,0,2,1,0,2,2,2,0,2,0,0],
            colors: 5, moves: 44, movesHard: 42,
            seed: 0x8F27BFDD33AA2F9F,
            archetype: "The Channel"
        ),
        .init(
            id: 154, mask: 0x156AD5ABFFFFF,
            jelly: [2,1,0,1,1,0,0,0,0,1,1,1,1,2,2,2,1,0,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 22, movesHard: 19,
            seed: 0x2D5F3996B2F4ABB4,
            archetype: "The Jetty"
        ),
        .init(
            id: 155, mask: 0x41C7CFDFFFFF,
            jelly: [0,0,0,0,1,1,1,1,1,0,0,0,1,0,2,0,1,0,1,0,0,0,2,0,0,0,0,0,0,0,2,1,1,0,2,0,0,0,2,1,2,0,0,0,0,0,0,0,0],
            colors: 5, moves: 29, movesHard: 28,
            seed: 0xCB96B350323F27C9,
            archetype: "The Funnel"
        ),
        .init(
            id: 156, mask: 0xD9B366CDBFFF,
            jelly: [1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,1,1,0,0,1,0,0,0,1,0,0,2,2,0,0,1,0,0,2,2,0,2,2,0],
            colors: 4, moves: 36, movesHard: 35,
            seed: 0x69CE2D09B189A3DE,
            archetype: "The Jetty"
        ),
        .init(
            id: 157, mask: 0x70E7FFFFFFFF,
            jelly: [0,2,2,2,1,0,0,2,1,1,1,1,1,0,0,1,1,1,1,0,0,0,0,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 6, moves: 21, movesHard: 18,
            seed: 0x805A6C330D41FF3,
            archetype: "The Lagoon"
        ),
        .init(
            id: 158, mask: 0x1C3C7CFDFFFFF,
            jelly: [1,0,0,0,0,0,1,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,2,1,1,0,0,0,0,0,0,1,1,0,1,0,0,0,2,1,1,2,0,0,0,0,2,2,2],
            colors: 6, moves: 46, movesHard: 44,
            seed: 0xA63D207CB01E9C08,
            archetype: "The Shelf"
        ),
        .init(
            id: 159, mask: 0xA952A54ABFFF,
            jelly: [2,1,1,1,0,0,0,2,1,2,1,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 4, moves: 18, movesHard: 16,
            seed: 0x46769C38316B1A1F,
            archetype: "The Jetty"
        ),
        .init(
            id: 160, mask: 0x1071F7FFFFFF,
            jelly: [1,1,0,1,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,2,2,1,0,0,1,0,0,2,1,1,1,2,0,0,0,2,2,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 26, movesHard: 25,
            seed: 0xE2AC13EFAEB39432,
            archetype: "The Funnel"
        ),
        .init(
            id: 161, mask: 0x1FFFFF1C38204,
            jelly: [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,2,0,1,2,1,1,1,1,0,0,0,2,1,1,2],
            colors: 5, moves: 21, movesHard: 18,
            seed: 0x81E48EAA2EFF1148,
            archetype: "The Pyramid"
        ),
        .init(
            id: 162, mask: 0x1C79F7FFFFFF,
            jelly: [0,0,0,0,0,0,1,1,0,0,0,0,0,1,1,0,0,0,0,0,0,1,1,1,0,0,2,0,2,1,1,1,2,0,0,2,1,1,0,0,0,0,2,2,0,0,0,0,0],
            colors: 6, moves: 41, movesHard: 40,
            seed: 0x1F1B0762AD488C5C,
            archetype: "The Shelf"
        ),
    ]
    private static let generated3: [LuauLevel] = [
        .init(
            id: 163, mask: 0xF1E3CFFFFFFF,
            jelly: [1,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,1,2,0,0,2,1,0,1,0,0,0,2,1,0,0,0,0,0,2,2,0,2,0],
            colors: 6, moves: 45, movesHard: 38,
            seed: 0xBD52811C2C930871,
            archetype: "The Well"
        ),
        .init(
            id: 164, mask: 0x1264C993FFFFF,
            jelly: [0,1,1,1,1,1,2,1,0,1,1,0,0,1,0,0,2,1,2,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 16, movesHard: 16,
            seed: 0x5D8BFCD7ADDF8688,
            archetype: "The Jetty"
        ),
        .init(
            id: 165, mask: 0x1FFFFF70E0810,
            jelly: [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,1,0,0,0,0,0,2,2,0,0,0,1,0,1,0,1,0,2,1,0,1,0,0,1,0,0,0,0,0,0,0],
            colors: 5, moves: 21, movesHard: 18,
            seed: 0xF9C1748F2B28009B,
            archetype: "The Pyramid"
        ),
        .init(
            id: 166, mask: 0x70E1CFFFFFFF,
            jelly: [0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,1,1,1,0,1,2,0,0,2,1,1,0,0,0,0,2,1,0,0,0,0,0,2,2,2,0,0],
            colors: 5, moves: 27, movesHard: 26,
            seed: 0x97F8EE48AA727CB0,
            archetype: "The Well"
        ),
        .init(
            id: 167, mask: 0x1BF7EFDFBF7EF,
            jelly: [2,1,1,2,0,0,0,1,1,1,1,0,0,0,1,1,1,1,0,0,0,2,1,1,2,0,0,0,2,1,1,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 21, movesHard: 18,
            seed: 0x373169032ABDF9C6,
            archetype: "The Channel"
        ),
        .init(
            id: 168, mask: 0x183878F9FFFFF,
            jelly: [1,0,0,0,0,0,1,1,0,0,0,0,0,1,2,1,0,0,0,0,0,0,0,2,1,1,1,0,0,0,0,2,1,1,2,0,0,0,0,0,2,2,0,0,0,0,0,0,0],
            colors: 5, moves: 28, movesHard: 27,
            seed: 0xD467E1BBA90774DA,
            archetype: "The Shelf"
        ),
        .init(
            id: 169, mask: 0x1FFFFFFFF1C10,
            jelly: [0,0,0,0,2,0,0,0,0,0,2,0,2,0,0,0,1,0,0,0,1,1,0,0,0,1,0,1,0,0,0,0,1,0,0,1,0,0,1,2,1,0,2,2,0,2,2,0,0],
            colors: 6, moves: 37, movesHard: 36,
            seed: 0x729F5B752851F0EF,
            archetype: "The Pyramid"
        ),
        .init(
            id: 170, mask: 0x1020E1C7FFFF,
            jelly: [0,0,0,0,1,0,1,1,0,0,0,0,1,2,2,0,0,1,2,0,0,0,0,1,2,0,0,0,0,2,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 31, movesHard: 30,
            seed: 0x10D6D52EA79C6D04,
            archetype: "The Funnel"
        ),
        .init(
            id: 171, mask: 0x156AD5AB57FFF,
            jelly: [2,2,0,2,1,1,2,0,2,1,0,0,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 4, moves: 16, movesHard: 16,
            seed: 0xB11050EA28E8EB1B,
            archetype: "The Jetty"
        ),
        .init(
            id: 172, mask: 0x41C7CFDFFFFF,
            jelly: [2,1,0,0,1,1,1,0,0,0,1,0,0,1,2,1,0,0,0,0,0,0,2,0,1,0,0,0,0,0,2,0,1,0,2,0,0,0,2,2,2,0,0,0,0,0,0,0,0],
            colors: 5, moves: 33, movesHard: 32,
            seed: 0x4D45C8A1A631652E,
            archetype: "The Funnel"
        ),
        .init(
            id: 173, mask: 0x1FFFFF1C38204,
            jelly: [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,1,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,1,0,1,2,0,0,0,0,0,2,2,2,1,1,2],
            colors: 5, moves: 20, movesHard: 20,
            seed: 0xEB7D425B257BE143,
            archetype: "The Pyramid"
        ),
        .init(
            id: 174, mask: 0xA952A55FFFFF,
            jelly: [2,1,1,0,1,1,2,2,1,1,0,0,0,1,2,0,2,0,2,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 21, movesHard: 21,
            seed: 0x89B4BC14A4C65D58,
            archetype: "The Jetty"
        ),
        .init(
            id: 175, mask: 0x2041C38FBFFF,
            jelly: [0,0,1,0,1,0,0,2,0,1,0,1,0,2,0,2,0,1,1,2,0,0,0,0,0,0,0,0,0,0,2,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 33, movesHard: 32,
            seed: 0x27EC35CE2410D96D,
            archetype: "The Funnel"
        ),
        .init(
            id: 176, mask: 0x1FFFFFFEF8E08,
            jelly: [0,0,0,2,0,0,0,0,0,2,0,2,0,0,0,2,0,0,0,1,0,1,0,0,0,0,0,1,1,0,0,1,0,0,1,0,1,1,0,0,0,1,2,2,2,2,0,0,0],
            colors: 6, moves: 32, movesHard: 31,
            seed: 0xC623AF87A35B5582,
            archetype: "The Pyramid"
        ),
        .init(
            id: 177, mask: 0x1264C99327FFF,
            jelly: [0,1,0,0,1,1,2,2,2,2,0,2,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 4, moves: 13, movesHard: 13,
            seed: 0x665D2B4324A7D399,
            archetype: "The Jetty"
        ),
        .init(
            id: 178, mask: 0x1EFDFBF7EFDFB,
            jelly: [2,2,0,2,1,1,0,2,1,0,1,1,1,1,0,0,0,2,1,1,0,2,0,0,0,1,1,0,0,0,0,0,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 4, moves: 42, movesHard: 36,
            seed: 0x292A2FB9C014DAD,
            archetype: "The Channel"
        ),
        .init(
            id: 179, mask: 0x1FFFFF3870408,
            jelly: [0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,2,1,0,1,2,1,2,0,2,1,2],
            colors: 5, moves: 30, movesHard: 29,
            seed: 0xA0CA1CB4213AC9C1,
            archetype: "The Pyramid"
        ),
        .init(
            id: 180, mask: 0x1071F7FFFFFF,
            jelly: [2,0,1,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,2,1,0,1,1,2,0,2,1,0,1,2,0,0,0,2,2,2,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 27, movesHard: 26,
            seed: 0x3F01966DA08545D6,
            archetype: "The Funnel"
        ),
        .init(
            id: 181, mask: 0xD9B366CDBFFF,
            jelly: [1,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,1,0,0,0,1,1,0,0,1,0,0,0,0,0,2,1,0,0,2,0,0,2,0,0,0,2,2,0,2,2,0],
            colors: 4, moves: 39, movesHard: 38,
            seed: 0xDD3910271FCFC1EB,
            archetype: "The Jetty"
        ),
        .init(
            id: 182, mask: 0x3870EFFFFFFF,
            jelly: [1,1,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,0,1,2,1,0,1,2,2,2,0,2,1,0,0,0,0,0,0,0,2,0,0,0,0,0,2,2,0,0,0],
            colors: 5, moves: 26, movesHard: 25,
            seed: 0x7B7089E09F1A3E00,
            archetype: "The Well"
        ),
        .init(
            id: 183, mask: 0x1C79F7FFFFFF,
            jelly: [0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,2,1,1,1,0,0,2,0,2,1,1,1,2,0,0,2,0,1,2,0,0,0,0,2,2,0,0,0,0],
            colors: 6, moves: 45, movesHard: 43,
            seed: 0x19A8039A1E64BA15,
            archetype: "The Shelf"
        ),
        .init(
            id: 184, mask: 0x70E1CFFFFF9C,
            jelly: [0,0,0,1,1,0,0,0,1,1,1,1,1,1,0,0,0,1,1,1,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 15, movesHard: 11,
            seed: 0xB8E07E549EB0372B,
            archetype: "The Cross"
        ),
        .init(
            id: 185, mask: 0x1BF7EFDFBF7EF,
            jelly: [2,0,1,2,0,0,2,1,1,1,0,0,1,1,2,1,0,2,0,2,1,2,1,1,2,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 4, moves: 30, movesHard: 26,
            seed: 0x5616F70E170AB240,
            archetype: "The Channel"
        ),
        .init(
            id: 186, mask: 0x70E1C39FFFFF,
            jelly: [0,1,0,0,0,0,1,0,0,0,0,0,0,1,2,1,0,0,0,1,0,0,0,2,1,2,0,0,0,0,0,1,0,0,0,0,0,2,1,0,0,0,0,0,2,2,2,0,0],
            colors: 5, moves: 30, movesHard: 29,
            seed: 0xF44E70C69C442E54,
            archetype: "The Well"
        ),
        .init(
            id: 187, mask: 0x73FFFFE70E1C,
            jelly: [0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,0,2,2,0,1,1,2,1,0,0,0,1,2,0,0,2,2,2,0,0],
            colors: 5, moves: 26, movesHard: 25,
            seed: 0x9285EA801B8EAA69,
            archetype: "The Cross"
        ),
        .init(
            id: 188, mask: 0x78F1E3DFFFFF,
            jelly: [1,1,1,1,1,1,0,1,1,1,1,1,0,0,1,1,1,1,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 18, movesHard: 13,
            seed: 0x32BF663B9CDB2880,
            archetype: "The Well"
        ),
        .init(
            id: 189, mask: 0x1E3C78FFFFFFF,
            jelly: [0,1,0,0,1,0,0,0,1,0,0,0,1,0,1,1,0,1,0,0,0,2,2,2,0,0,1,1,0,0,0,2,0,0,2,0,0,0,0,1,0,0,0,0,0,2,2,2,2],
            colors: 6, moves: 47, movesHard: 45,
            seed: 0xCEF4DDF31A23A293,
            archetype: "The Lagoon"
        ),
        .init(
            id: 190, mask: 0x1264C99327FFF,
            jelly: [2,0,0,0,1,0,2,2,2,2,1,2,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 4, moves: 13, movesHard: 13,
            seed: 0x6F2E59AE9B7020AA,
            archetype: "The Jetty"
        ),
        .init(
            id: 191, mask: 0x20E3EFFFFFFF,
            jelly: [2,0,0,0,0,0,2,1,0,0,0,0,0,1,2,0,0,0,0,0,1,0,0,0,1,1,1,2,0,2,1,1,1,0,0,0,0,2,2,2,0,0,0,0,0,0,0,0,0],
            colors: 6, moves: 42, movesHard: 41,
            seed: 0xB63D16618B89ABD,
            archetype: "The Funnel"
        ),
        .init(
            id: 192, mask: 0x1FFFFFFFFCE1C,
            jelly: [0,0,1,1,1,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,1,0,0,0,0,1,1,0,0,0,0,0,0],
            colors: 6, moves: 37, movesHard: 26,
            seed: 0xA99B4B1F980316D2,
            archetype: "The Lagoon"
        ),
        .init(
            id: 193, mask: 0x1071F7FFFFFF,
            jelly: [1,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,0,0,2,2,1,1,1,0,2,0,2,0,1,1,2,0,0,0,2,2,2,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 27, movesHard: 26,
            seed: 0x47D2C4D9174D92E7,
            archetype: "The Funnel"
        ),
        .init(
            id: 194, mask: 0x156AD5AB57FFF,
            jelly: [0,2,2,0,1,0,0,2,2,1,2,1,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 4, moves: 13, movesHard: 13,
            seed: 0xE80C4094989A10FE,
            archetype: "The Jetty"
        ),
        .init(
            id: 195, mask: 0x1020E1C7FFFF,
            jelly: [1,0,0,0,0,0,1,1,0,0,0,0,1,2,2,0,0,0,2,0,0,0,2,1,1,0,0,0,0,2,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 33, movesHard: 32,
            seed: 0x8441B84C15E28B11,
            archetype: "The Funnel"
        ),
        .init(
            id: 196, mask: 0x1FFFFF70E0810,
            jelly: [0,0,0,0,2,0,0,0,0,0,0,2,0,0,0,0,0,0,0,2,0,0,0,0,1,1,1,0,1,0,0,0,1,0,1,0,0,0,0,2,0,0,0,1,1,0,2,2,0],
            colors: 5, moves: 23, movesHard: 22,
            seed: 0x22793205952D0726,
            archetype: "The Pyramid"
        ),
        .init(
            id: 197, mask: 0xA952A54ABFFF,
            jelly: [2,0,1,0,1,0,2,2,0,2,1,2,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 4, moves: 24, movesHard: 23,
            seed: 0xC0B0ABBF1477833B,
            archetype: "The Jetty"
        ),
        .init(
            id: 198, mask: 0x4083871F3FFF,
            jelly: [1,0,0,0,0,0,1,2,1,0,0,0,0,1,0,0,2,0,0,0,2,0,0,0,2,1,1,0,0,0,0,2,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            colors: 5, moves: 34, movesHard: 33,
            seed: 0x5EE8257893C1FF50,
            archetype: "The Funnel"
        ),
        .init(
            id: 199, mask: 0x1FFFFF1C38204,
            jelly: [0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,1,1,2,2,2,2,1,1,2],
            colors: 5, moves: 27, movesHard: 26,
            seed: 0xFD1F9F32130C7B65,
            archetype: "The Pyramid"
        ),
        .init(
            id: 200, mask: 0x20E3EFFFFFFF,
            jelly: [2,1,1,0,0,0,2,0,0,0,0,0,0,1,0,0,0,0,0,0,2,0,1,1,1,1,1,2,0,2,0,1,0,2,0,0,0,2,2,0,0,0,0,0,0,0,0,0,0],
            colors: 6, moves: 41, movesHard: 40,
            seed: 0x9B5718EB9256F77A,
            archetype: "The Funnel"
        ),
    ]
    static let generated: [LuauLevel] = generated0 + generated1 + generated2 + generated3
}
